"""Go regex-based baseline parser.

Covers the common case of Go symbol extraction: packages, imports, type
definitions (structs, interfaces, type aliases), free functions, methods,
``const`` and ``var`` blocks, and call sites. Mirrors the RustParser /
JavaParser pattern: walk lines, track brace depth for context, emit
File → Package/Type → Function/Method → CALLS edges.

The parser is intentionally regex-based (no tree-sitter dependency). It
handles well-formatted single-line declarations and balanced braces.
Parenthesized ``const ( ... )`` and ``var ( ... )`` groups are parsed as
a block whose entries become Constant nodes. scip-go augments resolution
with type-aware cross-package information when the binary is installed.
"""

from __future__ import annotations

import re
from pathlib import Path

from descry.generate import BaseParser, is_generated_source, is_non_project_call


# Package declaration: `package foo`
_RE_PACKAGE = re.compile(r"^\s*package\s+([A-Za-z_][A-Za-z0-9_]*)")

# Single import: `import "foo/bar"` or `import alias "foo/bar"` or `import _ "foo/bar"`
_RE_IMPORT_SINGLE = re.compile(
    r'^\s*import\s+(?:[A-Za-z_][A-Za-z0-9_]*\s+|\.\s+|_\s+)?"([^"]+)"'
)

# Grouped import block start: `import (`
_RE_IMPORT_BLOCK_START = re.compile(r"^\s*import\s*\(")

# Inside-block import line: `"foo/bar"` or `alias "foo/bar"`
_RE_IMPORT_BLOCK_LINE = re.compile(
    r'^\s*(?:[A-Za-z_][A-Za-z0-9_]*\s+|\.\s+|_\s+)?"([^"]+)"'
)

# Type declaration: `type Name struct {`, `type Name interface {`, `type Name = AliasTarget`
_RE_TYPE_DECL = re.compile(
    r"^\s*type\s+([A-Z][A-Za-z0-9_]*)\s+"
    r"(struct|interface|func|chan|map|\[\]|\*|=|[A-Za-z])"
)

# Function (free) declaration: `func Name(...) ...`
_RE_FUNC = re.compile(r"^\s*func\s+([A-Za-z_][A-Za-z0-9_]*)\s*(?:\[[^]]+\])?\s*\(")

# Method declaration: `func (receiver *Type) Name(...)`
_RE_METHOD = re.compile(
    r"^\s*func\s+"
    r"\(\s*[A-Za-z_][A-Za-z0-9_]*\s+\*?\s*([A-Za-z_][A-Za-z0-9_]*)\s*\)\s+"
    r"([A-Za-z_][A-Za-z0-9_]*)\s*(?:\[[^]]+\])?\s*\("
)

# Const single-line: `const Name = value`
_RE_CONST_SINGLE = re.compile(
    r"^\s*const\s+([A-Z][A-Za-z0-9_]*)\s*(?:[A-Za-z0-9_\[\]]*\s*)?="
)

# Grouped const/var block: `const (` / `var (`
_RE_CONST_BLOCK_START = re.compile(r"^\s*const\s*\(")
_RE_VAR_BLOCK_START = re.compile(r"^\s*var\s*\(")

# Inside a const/var block: `Name = value` or `Name Type = value`
_RE_BLOCK_ENTRY = re.compile(r"^\s*([A-Za-z_][A-Za-z0-9_]*)\s+[A-Za-z0-9_.\[\]*]*\s*=?")

# Call site: `identifier(` or `receiver.method(`
_RE_CALL = re.compile(
    r"(?<![A-Za-z0-9_.])"
    r"([A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)*)"
    r"\s*\("
)

# Go control-flow keywords that would spuriously match the call regex.
_GO_CONTROL_KEYWORDS = frozenset(
    {
        "if",
        "for",
        "switch",
        "select",
        "return",
        "go",
        "defer",
        "func",
        "chan",
        "map",
        "range",
        "make",
        "new",
        "len",
        "cap",
        "append",
        "copy",
        "delete",
        "panic",
        "recover",
        "print",
        "println",
        "close",
    }
)


def _strip_line_comment(line: str) -> str:
    """Return `line` with any trailing ``//...`` comment removed.

    Tracks simple string state so ``"http://"`` is preserved. Does NOT
    handle block comments (``/* ... */``) — those spans are suppressed
    by a separate in-block flag tracked in the main loop.
    """
    in_string = False
    escape = False
    i = 0
    while i < len(line):
        c = line[i]
        if escape:
            escape = False
        elif c == "\\" and in_string:
            escape = True
        elif c == '"':
            in_string = not in_string
        elif not in_string and c == "/" and i + 1 < len(line) and line[i + 1] == "/":
            return line[:i]
        i += 1
    return line


class GoParser(BaseParser):
    """Regex-driven Go source parser."""

    def parse(self, _file_path, rel_path, content):
        file_id = f"FILE:{rel_path}"
        self.builder.add_node(
            file_id,
            "File",
            path=rel_path,
            name=Path(rel_path).name,
            token_count=len(content) // 4,
        )

        lines = content.splitlines()

        # Autogenerated Go files (protoc-gen-go, mockgen, wire,
        # moq, etc.) follow the well-known "// Code generated ... DO
        # NOT EDIT" convention. Their call graph is boilerplate that
        # never resolves to user code; SCIP indexers cover them
        # anyway. Skip CALLS emission from generated files — still
        # walk the structure so cross-file references to generated
        # types/functions can resolve.
        skip_calls = is_generated_source(content)

        # Package declaration
        package = None
        for line in lines[:30]:
            m = _RE_PACKAGE.match(line)
            if m:
                package = m.group(1)
                break
        if package:
            for node in self.builder.nodes:
                if node.get("id") == file_id:
                    node.setdefault("metadata", {})["go_package"] = package
                    break

        # Imports — single and grouped
        in_import_block = False
        in_const_block = False
        in_var_block = False
        current_context: list[str] = [file_id]
        type_name_stack: list[str] = []

        i = 0
        n = len(lines)
        in_block_comment = False
        while i < n:
            raw_line = lines[i]
            lineno = i + 1

            # Handle block comments (/* ... */). Spans longer than one line
            # are completely suppressed.
            stripped = raw_line.lstrip()
            if in_block_comment:
                if "*/" in raw_line:
                    in_block_comment = False
                i += 1
                continue
            if stripped.startswith("/*") and "*/" not in raw_line:
                in_block_comment = True
                i += 1
                continue

            # Strip any trailing `// comment` to keep the call regex honest
            # on lines like `// +k8s:alpha(since:"1.36")` where `alpha(`
            # would otherwise look like a method invocation.
            line = _strip_line_comment(raw_line)

            # Import block state machine
            if _RE_IMPORT_BLOCK_START.match(line):
                in_import_block = True
                i += 1
                continue
            if in_import_block:
                if line.strip().startswith(")"):
                    in_import_block = False
                    i += 1
                    continue
                m = _RE_IMPORT_BLOCK_LINE.match(line)
                if m:
                    self.builder.add_edge(file_id, f"MODULE:{m.group(1)}", "IMPORTS")
                i += 1
                continue

            m_imp = _RE_IMPORT_SINGLE.match(line)
            if m_imp:
                self.builder.add_edge(file_id, f"MODULE:{m_imp.group(1)}", "IMPORTS")
                i += 1
                continue

            # const / var block state machine
            if _RE_CONST_BLOCK_START.match(line):
                in_const_block = True
                i += 1
                continue
            if _RE_VAR_BLOCK_START.match(line):
                in_var_block = True
                i += 1
                continue
            if in_const_block or in_var_block:
                if line.strip().startswith(")"):
                    in_const_block = False
                    in_var_block = False
                    i += 1
                    continue
                m_entry = _RE_BLOCK_ENTRY.match(line)
                if m_entry and not line.strip().startswith("//"):
                    name = m_entry.group(1)
                    parent_id = current_context[-1]
                    const_id = f"{parent_id}::{name}"
                    if const_id not in self.builder.node_registry:
                        self.builder.add_node(
                            const_id,
                            "Constant",
                            name=name,
                            lineno=lineno,
                            docstring="",
                        )
                        self.builder.add_edge(parent_id, const_id, "DEFINES")
                i += 1
                continue

            # Type declarations
            m_type = _RE_TYPE_DECL.match(line)
            if m_type:
                name, kind = m_type.groups()
                parent_id = current_context[-1]
                type_id = f"{parent_id}::{name}"
                end_lineno = self._find_block_end(lines, i) if "{" in line else lineno
                docstring = self.get_leading_docstring(lines, i)
                self.builder.add_node(
                    type_id,
                    "Class",
                    name=name,
                    kind=kind if kind in ("struct", "interface") else "type",
                    lineno=lineno,
                    end_lineno=end_lineno,
                    token_count=(end_lineno - lineno + 1) * 10,
                    docstring=docstring,
                )
                self.builder.add_edge(parent_id, type_id, "DEFINES")
                if "{" in line and kind in ("struct", "interface"):
                    current_context.append(type_id)
                    type_name_stack.append(name)
                i += 1
                continue

            # Methods (receiver-bound)
            m_method = _RE_METHOD.match(line)
            if m_method:
                receiver_type, method_name = m_method.groups()
                # Method lives under its receiver type.
                method_id = f"{file_id}::{receiver_type}::{method_name}"
                end_lineno = self._find_block_end(lines, i) if "{" in line else lineno
                docstring = self.get_leading_docstring(lines, i)
                self.builder.add_node(
                    method_id,
                    "Method",
                    name=method_name,
                    lineno=lineno,
                    end_lineno=end_lineno,
                    token_count=(end_lineno - lineno + 1) * 10,
                    docstring=docstring,
                    receiver=receiver_type,
                )
                self.builder.add_edge(
                    f"{file_id}::{receiver_type}", method_id, "DEFINES"
                )
                # Push the method body as call-attribution context. Without
                # this, calls inside method bodies attribute to the file and
                # get dropped by the `current_context[-1] != file_id` gate
                # — so the parser used to emit only ~1-2 calls per Go file.
                if "{" in line:
                    current_context.append(method_id)
                    type_name_stack.append(method_name)
                i += 1
                continue

            # Free functions
            m_func = _RE_FUNC.match(line)
            if m_func and "func(" not in line.replace(" ", ""):
                # Exclude `func(x int) ...` anonymous-style (the lookbehind is
                # approximate; the strict check is that `func` is followed by
                # an identifier before the `(`, which _RE_FUNC already enforces).
                name = m_func.group(1)
                parent_id = current_context[-1]
                func_id = f"{parent_id}::{name}"
                end_lineno = self._find_block_end(lines, i) if "{" in line else lineno
                docstring = self.get_leading_docstring(lines, i)
                self.builder.add_node(
                    func_id,
                    "Function",
                    name=name,
                    lineno=lineno,
                    end_lineno=end_lineno,
                    token_count=(end_lineno - lineno + 1) * 10,
                    docstring=docstring,
                )
                self.builder.add_edge(parent_id, func_id, "DEFINES")
                if "{" in line:
                    current_context.append(func_id)
                    type_name_stack.append(name)
                i += 1
                continue

            # Single-line const / var
            m_const = _RE_CONST_SINGLE.match(line)
            if m_const:
                name = m_const.group(1)
                parent_id = current_context[-1]
                const_id = f"{parent_id}::{name}"
                if const_id not in self.builder.node_registry:
                    self.builder.add_node(
                        const_id,
                        "Constant",
                        name=name,
                        lineno=lineno,
                        docstring="",
                    )
                    self.builder.add_edge(parent_id, const_id, "DEFINES")

            # Calls — regex path (no ast-grep Go backend today).
            # Skipped entirely for autogenerated files.
            if not skip_calls and current_context[-1] != file_id:
                parent_id = current_context[-1]
                for call_match in _RE_CALL.finditer(line):
                    callee = call_match.group(1)
                    simple = callee.split(".")[-1]
                    if simple in _GO_CONTROL_KEYWORDS:
                        continue
                    if is_non_project_call(callee):
                        continue
                    self.builder.edges.append(
                        {
                            "source": parent_id,
                            "target": f"REF:{callee}",
                            "relation": "CALLS",
                            "metadata": {"lineno": lineno},
                        }
                    )

            # Pop on closing brace
            if "}" in line and len(current_context) > 1:
                close = line.count("}")
                open_ = line.count("{")
                net = close - open_
                for _ in range(max(0, net)):
                    if len(current_context) > 1:
                        current_context.pop()
                        if type_name_stack:
                            type_name_stack.pop()

            i += 1
